---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: >-
        aEVUYy9ndzem1x+fY5R4glyWiq0ncn6UgARleZ9l8lSHTMT/ZvgHGyWd98DcSEKsFRp
        rhv2VsVAaqQCVR01Y839NeD6jKVDnakORdc4H+T5e+hhm5TY9VbTikDhX4pEMixA/+w
        X7PuVjVbxZLUUZ3COs8bbPc2x2b9AooFgeC2vG324yeLBxyXrHPUuomtNUj+PaEZ+md
        JyvFgvvcIo+LmNaP7O8/qSZ9y3V1fxhj4bAMA7vk8/qW6k9yH8vtfkdcYvdgZgfwu7y
        c68QKmuBN6M7EZ7BSpbiuo8AS7NzBdg7pNyEa8q0M6pY738RB5SIluycyjU9ofCaqlH
        RXdJacCfIncBZCT3miQtTXFV0pEjBS3FaiCB63qx5WqGMI+t/HsqY54QuSmsQoVbOAx
        G78B/e/CV7c9RmOkuhEvcdtUg6j3ETw9eMidd4B2EhXhiXjpJHfTuq2g0Dfgl+iyXje
        +QT2YS2qXXuYuys/YVCzifjQbP3H9v9Cvo1Ftza1YzgjsBRoSGrZUuUIuNun4lF297n
        DncYEeG7rxoNsmqbYjAY7gZriYEvp3jxR97XjbOSvdIaFVKKb0r8Wfhmvmm8ehqao9z
        Jcl8daVD5wqR3vcXXew6rkiQ+/rkB7KwBtMh/jTKO3D6XP8K4vZbrfLcVOZYFP8bEaV
        JjWJ1PraLFhcs=
    # AWS_SECRET_ACCESS_KEY
    - secure: >-
        XYLwd5bvFIdw9Tx/yRDhpmj8DyGx2Fv5aPjB37lNPRWEswab0YO56TjxqNTEbgcOeIW
        /kqwTJT6oQEE8TEX1xUvrpg+0WlN67kwi4MVsGb9eVAwbiLnEh3ji55JwMMGtWwxPlo
        6oGAZXfYyvsf/UHe62h94Mo9T5V5kdVtDVro4avTz9YFMI0qnkpOFcz5V/+6cEJpWKL
        mzSiXUipx5pWmZPmhF2MYuGf4fwhOVuyYySvPI3zOizHF0ywhYRjUOKpHnj26WQ6hX9
        8UV+qxpQtspODuOCnY7N/u/+Yj2ZQ9rMvNRdUeYQRN6jvYoOtxSGfrObLiwI8vMQhNZ
        g/kVuggFviNbfdJ7h2kNObFqWftlik1z5146tkQnD3OPQ7Quef6W2DE+VIVGi/rsu7R
        AXbpYvrK3+Ql12yDpmfJFzaozHM/Hwzm+emUuuA5NxqBcVjYIxaRH43FL2LkYCZkCQd
        pC6p4yCKW3A7NAC+cMoZuNj5ZAqI3yw6TTVf6F4u4MDBd+retNZZZjTE0S5RBZ+HTmu
        gB95WFKyrY5AVIo9rQ3K85lv+WYHAmu4pzAtNCWtEEVEnECiDCg67j0B1PRpnCRApRO
        xsIBHQjjzhEOy7GvWD5D8luK8anHtmOp+jUL8BFUtAuuPMuP1rCxOPuSekrff2yjWpb
        vD4IUsTftHaBs=
    - BUILD_REGION="us-east-2"
    - DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - PACKER_VERSION="1.4.1"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

before_install:
  # Install terraform and terraform-doc
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs
  # install packer.io
  - curl --output /tmp/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export IMAGE_VERSION=$(./bump_version.sh show)
  - eval $(./update_env.py)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create a production image
  - provider: script
    script: packer build --timestamp-ui src/packer.json
    on:
      tags: true
  # # create a testing image
  # - provider: script
  #   script: export IMAGE_VERSION=${IMAGE_VERSION}-pre &&
  #     packer build src/packer.json
  #   on:
  #     tags: false
