---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: >-
        es7MJoLiX5OzAyRVw5DVQOBhpo7e5EPdh7qX2dOCI0W2IZcjYAnK2us4KiIKipe6EUt
        3utVVRHSEeVkENoh+McBqp3yk53CHzHjX855oMkpwWA5qu9bofBaSDEzQWORmc44Eov
        z6ZgxbG6gXJzWO2lsOWA8hd+5Z1C9O/2PQdjatgZZPmM42PpGs7PG6Hf/bF0Fgtg36G
        MApMJmocXfxJrqcWhdhg0px9o5CDPF6v2CcTrmsQxJj0v3w45M4VPDFNFEdKfTW2a/m
        kDAidMNGn2ugTzTpga6AxUzF1MyJ4+7AuItax4uUxFUmOh2mXTLtFKo9FJAXdffftzj
        mnhPloaQdvFzFUKJoz3f6tBqGP3ae8UTEXYdBuPC6/VhRsI4LiQ5tVeC5pqvmW4PqHQ
        Sk9rs0gJ4GtSnmI5+hGAOpVUgLTQ6awujBZER2ApObyi7vh+WrxinGZajZcng0FtV1p
        +sueoQw4U8X6CwD9UOxEcd0Xnp3chMUWUowVgs5/5lO3vaKRM+RfvQH3bsKGN4mRlf0
        HBvLW+4iSTDvpBaHCVr/m53hERGkdrQa44fVZqE9cXTvCwtAa1UsmwnqbNDRdhE4Dr9
        vrAsfwXG4nKXrNmQ2nsZbbUXGqUP7i0sjXFdWD0HFo474+U6uDjtOmKcby5l+SyBnwl
        ke3/yWoyLnisA=
    # AWS_SECRET_ACCESS_KEY
    - secure: >-
        c7Qo6tdi0ihKBHNjNMgBiCpHJdT7TIUixXCK8eHxAl4SI4Sv6Ygv/hQFzkBuk7Y3/kj
        uxUbxF8IAnmgTzGDxjTNHAY8fNNe8banlVUi83QlfjYr9AnHb36wXWcdTivmbzbfUMk
        PH0QECCC9q/TcqtCizIKMgU6V7NoZxPzwf9bFtGdSjpy5yfnyZpIbzctBP1NMlw+SrP
        K4LD+9k05Q9Im24cHEs7UQJhXew+c60nBRod2HdRynFYe8Eru5QwsYfbRc9ko0zTEqK
        5RTWPYQi50uSe6iTJCK3zHh7cGFQ31gh1bhX2MGvssM/qONMetfogLl0uzQ1wsXP+4Q
        4ufWq2dT/m0cYyuwVQokAhgjd5oevK+VHbSsH2g1/uczlaEV9vn+MP6QJOAVuDWVrkC
        r0EaGFT/iSQG7xN+XWln/mSN+AOwE++AYPNZ+eDONo57aaUqlQq+1o3ardbV3cId6QE
        CUV4ltwpl1nX9WjYCqqvKLav9DGKSVTfPe2aCV+ugooroOjD93Kj6HSJrqM9veqLP+5
        fqQ8bDKxafJatOVN4hyYhbVn4UN//U2thSGMu0t20kjIIDFIodRlCGTVXWLyxN7NPMp
        7QGm04M3ZRyYkZgof0UkSaCJLB6ClZS1AfK4RSeuiUBAi4b8n/R/RNuzwpHoLyJSix7
        QIukSTRw5n6t4=
    - PACKER_BUILD_REGION="us-east-2"
    - PACKER_DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - PACKER_VERSION="1.4.2"
    - TERRAFORM_VERSION="0.12.3"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

before_install:
  # Install terraform
  - >
    wget
    https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    -O /tmp/terraform.zip
  - sudo unzip -d /opt/terraform /tmp/terraform.zip
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  # install packer
  - curl --output /tmp/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export PACKER_IMAGE_VERSION=$(./bump_version.sh show)
  - eval $(./update_env.py)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create a production image
  - provider: script
    script: packer build --timestamp-ui src/packer.json
    on:
      tags: true
