---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import Example playbook
  ansible.builtin.import_playbook: example.yml
