---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import OpenVPN playbook
  ansible.builtin.import_playbook: openvpn.yml

- name: Import CISA CDM playbook
  ansible.builtin.import_playbook: cdm.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import hardening playbook
  ansible.builtin.import_playbook: harden.yml
