---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - freeipa_client
    - persist_journald
    - htop
    - clamav

- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    - amazon_ssm_agent
    - cloudwatch_agent
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme

- hosts: openvpn
  name: Project-specific roles
  become: yes
  become_method: sudo
  roles:
    - openvpn
