---
- name: Install and configure ufw
  hosts: all
  vars:
    outgoing_only_ports:
      - port: http
        proto: tcp
      - port: https
        proto: tcp
      - port: domain
        proto: tcp
      - port: domain
        proto: udp
  become: yes
  become_method: sudo
  roles:
    - ufw
  tasks:
    - name: Set default policies to deny
      ufw:
        default: deny
        direction: "{{ item }}"
      loop:
        - incoming
        - outgoing
    # The OpenVPN port is already opened in
    # cisagov/ansible-role-openvpn
    - name: Allow ssh only from localhost
      ufw:
        comment: Allow ssh only from localhost
        direction: in
        interface: lo
        proto: tcp
        rule: allow
        to_port: ssh
    - name: Allow outgoing traffic
      ufw:
        comment: Allow {{ item.port }} via {{ item.proto | upper }}
        direction: out
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ outgoing_only_ports }}"
