---
- hosts: all
  name: Install and configure ufw
  become: yes
  become_method: sudo
  roles:
    - ufw
  tasks:
    # The OpenVPN port is already opened in
    # cisagov/ansible-role-openvpn
    - name: Allow ssh only from localhost
      ufw:
        comment: Allow ssh only from localhost
        direction: in
        interface: lo
        proto: tcp
        rule: allow
        to_port: ssh
