---
name: build

on:
  push:

env:
  CURL_CACHE_DIR: $HOME/.cache/curl

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup cache # GitHub support coming soon
        run: mkdir -p $CURL_CACHE_DIR
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements-test.txt
      - name: Run linters on all files
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: cisagov/setup-env-github-action@develop
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup cache # GitHub support coming soon
        run: mkdir -p $CURL_CACHE_DIR
      - name: Install Packer
        run: |
          PACKER_ZIP="packer_${PACKER_VERSION}_linux_amd64.zip"
          curl --output "${CURL_CACHE_DIR}/${PACKER_ZIP}" \
            --time-cond "${CURL_CACHE_DIR}/${PACKER_ZIP}" --location \
            "https://releases.hashicorp.com/packer/${PACKER_VERSION}/${PACKER_ZIP}"
          sudo unzip -o -d /usr/local/bin "${CURL_CACHE_DIR}/${PACKER_ZIP}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements-test.txt
      - name: Validate Packer configuration
        run: packer validate src/packer.json
      - name: Run tests
        env:
          GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest
